export default {
    LoginBackground: require("../assets/images/applogo.png"),
    EYE_OFF:require('../assets/images/eye_off.png'),
    EYE_ON:require('../assets/images/eye_on.png'),
    EMAIL_LOGIN:require('../assets/images/email_login.png'),
    PASSWORD_LOGIN:require('../assets/images/password_login.png'),
    FACEBOOK:require('../assets/images/Facebook.png'),
    TWITTER:require('../assets/images/Twitter.png'),
    GOOGLE:require('../assets/images/Google.png'),
    BACK_ICON:require('../assets/images/back_icon.png'),
    PHONE_ICON:require('../assets/images/phone.png'),
    ONBOARDING_PAGEONE:require('../assets/images/onboarding_pageone.png'),
    ONBOARDING_PAGETWO:require('../assets/images/onboarding_pagetwo.png'),
    ONBOARDING_PAGE_THREE:require('../assets/images/onBoarding_pagefour.png'),
    HOME_MAP:require('../assets/images/maps.jpg'),
    CAR_RIDE:require('../assets/images/car_ride.png'),
    CAR_RIDE_ACTIVE:require('../assets/images/car_ride_active.png'),
    SEARCH_RIDE:require('../assets/images/search_ride.png'),
    SEARCH_RIDE_ACTIVE:require('../assets/images/search_ride_active.png'),
    STARTNG_POINT_ICON:require('../assets/images/starting_point.png'),
    RIDE_TIME_ICON:require('../assets/images/ride_time.png'),
    NUMBER_OF_SEAT_ICON:require('../assets/images/number_seat.png'),
    NOTE_ICON:require('../assets/images/Note.png'),
    PIN_ICON:require('../assets/images/pin-3.png'),
    RIDE_VEHICLE:require('../assets/images/ride_vehicle.png'),
    DASHBOARD_ICON:require('../assets/images/dashboard_icon.png'),
    PAYMENT_ICON:require('../assets/images/payment_icon.png'),
    MY_VEHICLE_ICON:require('../assets/images/my_vehicles_icon.png'),
    CHAT_ICON:require('../assets/images/chat_icon.png'),
    GROUP_ICON:require('../assets/images/group_icon.png'),
    KING_ICON:require('../assets/images/king.png'),
    ACCOUNT_SWITCH_ICON:require('../assets/images/switch_icon.png'),


}